/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ABooleansSinglevalue extends PSinglevalue
{
    private PBooleans _booleans_;

    public ABooleansSinglevalue()
    {
        // Constructor
    }

    public ABooleansSinglevalue(
        @SuppressWarnings("hiding") PBooleans _booleans_)
    {
        // Constructor
        setBooleans(_booleans_);

    }

    @Override
    public Object clone()
    {
        return new ABooleansSinglevalue(
            cloneNode(this._booleans_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleansSinglevalue(this);
    }

    public PBooleans getBooleans()
    {
        return this._booleans_;
    }

    public void setBooleans(PBooleans node)
    {
        if(this._booleans_ != null)
        {
            this._booleans_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleans_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleans_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleans_ == child)
        {
            this._booleans_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleans_ == oldChild)
        {
            setBooleans((PBooleans) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
