/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ACmpOperations extends POperations
{
    private PCmp _cmp_;

    public ACmpOperations()
    {
        // Constructor
    }

    public ACmpOperations(
        @SuppressWarnings("hiding") PCmp _cmp_)
    {
        // Constructor
        setCmp(_cmp_);

    }

    @Override
    public Object clone()
    {
        return new ACmpOperations(
            cloneNode(this._cmp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACmpOperations(this);
    }

    public PCmp getCmp()
    {
        return this._cmp_;
    }

    public void setCmp(PCmp node)
    {
        if(this._cmp_ != null)
        {
            this._cmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cmp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cmp_ == child)
        {
            this._cmp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cmp_ == oldChild)
        {
            setCmp((PCmp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
