/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultProgramme extends PProgramme
{
    private PFunction _function_;
    private PProgramme _programme_;

    public ADefaultProgramme()
    {
        // Constructor
    }

    public ADefaultProgramme(
        @SuppressWarnings("hiding") PFunction _function_,
        @SuppressWarnings("hiding") PProgramme _programme_)
    {
        // Constructor
        setFunction(_function_);

        setProgramme(_programme_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultProgramme(
            cloneNode(this._function_),
            cloneNode(this._programme_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultProgramme(this);
    }

    public PFunction getFunction()
    {
        return this._function_;
    }

    public void setFunction(PFunction node)
    {
        if(this._function_ != null)
        {
            this._function_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._function_ = node;
    }

    public PProgramme getProgramme()
    {
        return this._programme_;
    }

    public void setProgramme(PProgramme node)
    {
        if(this._programme_ != null)
        {
            this._programme_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programme_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._function_)
            + toString(this._programme_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._function_ == child)
        {
            this._function_ = null;
            return;
        }

        if(this._programme_ == child)
        {
            this._programme_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._function_ == oldChild)
        {
            setFunction((PFunction) newChild);
            return;
        }

        if(this._programme_ == oldChild)
        {
            setProgramme((PProgramme) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
