/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AGlobalvarFunctionglobalvar extends PFunctionglobalvar
{
    private PParameters _parameters_;

    public AGlobalvarFunctionglobalvar()
    {
        // Constructor
    }

    public AGlobalvarFunctionglobalvar(
        @SuppressWarnings("hiding") PParameters _parameters_)
    {
        // Constructor
        setParameters(_parameters_);

    }

    @Override
    public Object clone()
    {
        return new AGlobalvarFunctionglobalvar(
            cloneNode(this._parameters_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGlobalvarFunctionglobalvar(this);
    }

    public PParameters getParameters()
    {
        return this._parameters_;
    }

    public void setParameters(PParameters node)
    {
        if(this._parameters_ != null)
        {
            this._parameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameters_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameters_ == child)
        {
            this._parameters_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parameters_ == oldChild)
        {
            setParameters((PParameters) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
