/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIdentifidentifSingleexpression extends PSingleexpression
{
    private TIdentif _first_;
    private PCmp _cmp_;
    private TIdentif _second_;

    public AIdentifidentifSingleexpression()
    {
        // Constructor
    }

    public AIdentifidentifSingleexpression(
        @SuppressWarnings("hiding") TIdentif _first_,
        @SuppressWarnings("hiding") PCmp _cmp_,
        @SuppressWarnings("hiding") TIdentif _second_)
    {
        // Constructor
        setFirst(_first_);

        setCmp(_cmp_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new AIdentifidentifSingleexpression(
            cloneNode(this._first_),
            cloneNode(this._cmp_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentifidentifSingleexpression(this);
    }

    public TIdentif getFirst()
    {
        return this._first_;
    }

    public void setFirst(TIdentif node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PCmp getCmp()
    {
        return this._cmp_;
    }

    public void setCmp(PCmp node)
    {
        if(this._cmp_ != null)
        {
            this._cmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cmp_ = node;
    }

    public TIdentif getSecond()
    {
        return this._second_;
    }

    public void setSecond(TIdentif node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._cmp_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._cmp_ == child)
        {
            this._cmp_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((TIdentif) newChild);
            return;
        }

        if(this._cmp_ == oldChild)
        {
            setCmp((PCmp) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((TIdentif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
