/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALogOperations extends POperations
{
    private PLog _log_;

    public ALogOperations()
    {
        // Constructor
    }

    public ALogOperations(
        @SuppressWarnings("hiding") PLog _log_)
    {
        // Constructor
        setLog(_log_);

    }

    @Override
    public Object clone()
    {
        return new ALogOperations(
            cloneNode(this._log_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogOperations(this);
    }

    public PLog getLog()
    {
        return this._log_;
    }

    public void setLog(PLog node)
    {
        if(this._log_ != null)
        {
            this._log_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._log_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._log_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._log_ == child)
        {
            this._log_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._log_ == oldChild)
        {
            setLog((PLog) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
