/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import java.util.*;
import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALoop extends PLoop
{
    private TWhile _while_;
    private TLp _lp_;
    private PExpression _expression_;
    private TRp _rp_;
    private TDo _do_;
    private TStartfunc _startfunc_;
    private final LinkedList<PInstruction> _instruction_ = new LinkedList<PInstruction>();
    private TEndfunc _endfunc_;

    public ALoop()
    {
        // Constructor
    }

    public ALoop(
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") TLp _lp_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TRp _rp_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") TStartfunc _startfunc_,
        @SuppressWarnings("hiding") List<?> _instruction_,
        @SuppressWarnings("hiding") TEndfunc _endfunc_)
    {
        // Constructor
        setWhile(_while_);

        setLp(_lp_);

        setExpression(_expression_);

        setRp(_rp_);

        setDo(_do_);

        setStartfunc(_startfunc_);

        setInstruction(_instruction_);

        setEndfunc(_endfunc_);

    }

    @Override
    public Object clone()
    {
        return new ALoop(
            cloneNode(this._while_),
            cloneNode(this._lp_),
            cloneNode(this._expression_),
            cloneNode(this._rp_),
            cloneNode(this._do_),
            cloneNode(this._startfunc_),
            cloneList(this._instruction_),
            cloneNode(this._endfunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoop(this);
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public TLp getLp()
    {
        return this._lp_;
    }

    public void setLp(TLp node)
    {
        if(this._lp_ != null)
        {
            this._lp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lp_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TRp getRp()
    {
        return this._rp_;
    }

    public void setRp(TRp node)
    {
        if(this._rp_ != null)
        {
            this._rp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rp_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public TStartfunc getStartfunc()
    {
        return this._startfunc_;
    }

    public void setStartfunc(TStartfunc node)
    {
        if(this._startfunc_ != null)
        {
            this._startfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startfunc_ = node;
    }

    public LinkedList<PInstruction> getInstruction()
    {
        return this._instruction_;
    }

    public void setInstruction(List<?> list)
    {
        for(PInstruction e : this._instruction_)
        {
            e.parent(null);
        }
        this._instruction_.clear();

        for(Object obj_e : list)
        {
            PInstruction e = (PInstruction) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._instruction_.add(e);
        }
    }

    public TEndfunc getEndfunc()
    {
        return this._endfunc_;
    }

    public void setEndfunc(TEndfunc node)
    {
        if(this._endfunc_ != null)
        {
            this._endfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endfunc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._while_)
            + toString(this._lp_)
            + toString(this._expression_)
            + toString(this._rp_)
            + toString(this._do_)
            + toString(this._startfunc_)
            + toString(this._instruction_)
            + toString(this._endfunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._lp_ == child)
        {
            this._lp_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._rp_ == child)
        {
            this._rp_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._startfunc_ == child)
        {
            this._startfunc_ = null;
            return;
        }

        if(this._instruction_.remove(child))
        {
            return;
        }

        if(this._endfunc_ == child)
        {
            this._endfunc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._lp_ == oldChild)
        {
            setLp((TLp) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._rp_ == oldChild)
        {
            setRp((TRp) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._startfunc_ == oldChild)
        {
            setStartfunc((TStartfunc) newChild);
            return;
        }

        for(ListIterator<PInstruction> i = this._instruction_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInstruction) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._endfunc_ == oldChild)
        {
            setEndfunc((TEndfunc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
