/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import java.util.*;
import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMain extends PMain
{
    private TMainfunc _mainfunc_;
    private PParameters _parameters_;
    private TStartfunc _startfunc_;
    private final LinkedList<PInstruction> _instruction_ = new LinkedList<PInstruction>();
    private TEndfunc _endfunc_;

    public AMain()
    {
        // Constructor
    }

    public AMain(
        @SuppressWarnings("hiding") TMainfunc _mainfunc_,
        @SuppressWarnings("hiding") PParameters _parameters_,
        @SuppressWarnings("hiding") TStartfunc _startfunc_,
        @SuppressWarnings("hiding") List<?> _instruction_,
        @SuppressWarnings("hiding") TEndfunc _endfunc_)
    {
        // Constructor
        setMainfunc(_mainfunc_);

        setParameters(_parameters_);

        setStartfunc(_startfunc_);

        setInstruction(_instruction_);

        setEndfunc(_endfunc_);

    }

    @Override
    public Object clone()
    {
        return new AMain(
            cloneNode(this._mainfunc_),
            cloneNode(this._parameters_),
            cloneNode(this._startfunc_),
            cloneList(this._instruction_),
            cloneNode(this._endfunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMain(this);
    }

    public TMainfunc getMainfunc()
    {
        return this._mainfunc_;
    }

    public void setMainfunc(TMainfunc node)
    {
        if(this._mainfunc_ != null)
        {
            this._mainfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mainfunc_ = node;
    }

    public PParameters getParameters()
    {
        return this._parameters_;
    }

    public void setParameters(PParameters node)
    {
        if(this._parameters_ != null)
        {
            this._parameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameters_ = node;
    }

    public TStartfunc getStartfunc()
    {
        return this._startfunc_;
    }

    public void setStartfunc(TStartfunc node)
    {
        if(this._startfunc_ != null)
        {
            this._startfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startfunc_ = node;
    }

    public LinkedList<PInstruction> getInstruction()
    {
        return this._instruction_;
    }

    public void setInstruction(List<?> list)
    {
        for(PInstruction e : this._instruction_)
        {
            e.parent(null);
        }
        this._instruction_.clear();

        for(Object obj_e : list)
        {
            PInstruction e = (PInstruction) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._instruction_.add(e);
        }
    }

    public TEndfunc getEndfunc()
    {
        return this._endfunc_;
    }

    public void setEndfunc(TEndfunc node)
    {
        if(this._endfunc_ != null)
        {
            this._endfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endfunc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mainfunc_)
            + toString(this._parameters_)
            + toString(this._startfunc_)
            + toString(this._instruction_)
            + toString(this._endfunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mainfunc_ == child)
        {
            this._mainfunc_ = null;
            return;
        }

        if(this._parameters_ == child)
        {
            this._parameters_ = null;
            return;
        }

        if(this._startfunc_ == child)
        {
            this._startfunc_ = null;
            return;
        }

        if(this._instruction_.remove(child))
        {
            return;
        }

        if(this._endfunc_ == child)
        {
            this._endfunc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mainfunc_ == oldChild)
        {
            setMainfunc((TMainfunc) newChild);
            return;
        }

        if(this._parameters_ == oldChild)
        {
            setParameters((PParameters) newChild);
            return;
        }

        if(this._startfunc_ == oldChild)
        {
            setStartfunc((TStartfunc) newChild);
            return;
        }

        for(ListIterator<PInstruction> i = this._instruction_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInstruction) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._endfunc_ == oldChild)
        {
            setEndfunc((TEndfunc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
