/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleExpression extends PExpression
{
    private PSingleexpression _singleexpression_;
    private PLog _log_;
    private PExpression _expression_;

    public AMultipleExpression()
    {
        // Constructor
    }

    public AMultipleExpression(
        @SuppressWarnings("hiding") PSingleexpression _singleexpression_,
        @SuppressWarnings("hiding") PLog _log_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setSingleexpression(_singleexpression_);

        setLog(_log_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleExpression(
            cloneNode(this._singleexpression_),
            cloneNode(this._log_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleExpression(this);
    }

    public PSingleexpression getSingleexpression()
    {
        return this._singleexpression_;
    }

    public void setSingleexpression(PSingleexpression node)
    {
        if(this._singleexpression_ != null)
        {
            this._singleexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleexpression_ = node;
    }

    public PLog getLog()
    {
        return this._log_;
    }

    public void setLog(PLog node)
    {
        if(this._log_ != null)
        {
            this._log_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._log_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._singleexpression_)
            + toString(this._log_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._singleexpression_ == child)
        {
            this._singleexpression_ = null;
            return;
        }

        if(this._log_ == child)
        {
            this._log_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._singleexpression_ == oldChild)
        {
            setSingleexpression((PSingleexpression) newChild);
            return;
        }

        if(this._log_ == oldChild)
        {
            setLog((PLog) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
