/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultivarRealvar extends PRealvar
{
    private PVar _var_;
    private POp _op_;
    private PRealvar _realvar_;

    public AMultivarRealvar()
    {
        // Constructor
    }

    public AMultivarRealvar(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") POp _op_,
        @SuppressWarnings("hiding") PRealvar _realvar_)
    {
        // Constructor
        setVar(_var_);

        setOp(_op_);

        setRealvar(_realvar_);

    }

    @Override
    public Object clone()
    {
        return new AMultivarRealvar(
            cloneNode(this._var_),
            cloneNode(this._op_),
            cloneNode(this._realvar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultivarRealvar(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public POp getOp()
    {
        return this._op_;
    }

    public void setOp(POp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    public PRealvar getRealvar()
    {
        return this._realvar_;
    }

    public void setRealvar(PRealvar node)
    {
        if(this._realvar_ != null)
        {
            this._realvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realvar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._op_)
            + toString(this._realvar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        if(this._realvar_ == child)
        {
            this._realvar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((POp) newChild);
            return;
        }

        if(this._realvar_ == oldChild)
        {
            setRealvar((PRealvar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
