/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ANotequalCmp extends PCmp
{
    private TNotequal _notequal_;

    public ANotequalCmp()
    {
        // Constructor
    }

    public ANotequalCmp(
        @SuppressWarnings("hiding") TNotequal _notequal_)
    {
        // Constructor
        setNotequal(_notequal_);

    }

    @Override
    public Object clone()
    {
        return new ANotequalCmp(
            cloneNode(this._notequal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotequalCmp(this);
    }

    public TNotequal getNotequal()
    {
        return this._notequal_;
    }

    public void setNotequal(TNotequal node)
    {
        if(this._notequal_ != null)
        {
            this._notequal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notequal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._notequal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._notequal_ == child)
        {
            this._notequal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._notequal_ == oldChild)
        {
            setNotequal((TNotequal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
