/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import java.util.*;
import sc.analysis.*;

@SuppressWarnings("nls")
public final class AProgramme extends PProgramme
{
    private final LinkedList<TIdentif> _identif_ = new LinkedList<TIdentif>();

    public AProgramme()
    {
        // Constructor
    }

    public AProgramme(
        @SuppressWarnings("hiding") List<?> _identif_)
    {
        // Constructor
        setIdentif(_identif_);

    }

    @Override
    public Object clone()
    {
        return new AProgramme(
            cloneList(this._identif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramme(this);
    }

    public LinkedList<TIdentif> getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(List<?> list)
    {
        for(TIdentif e : this._identif_)
        {
            e.parent(null);
        }
        this._identif_.clear();

        for(Object obj_e : list)
        {
            TIdentif e = (TIdentif) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._identif_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TIdentif> i = this._identif_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TIdentif) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
