/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AReadInstruction extends PInstruction
{
    private TIdentif _identif_;
    private PTablevalues _tablevalues_;
    private TEqual _equal_;
    private TRead _read_;
    private TPv _pv_;

    public AReadInstruction()
    {
        // Constructor
    }

    public AReadInstruction(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") PTablevalues _tablevalues_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") TRead _read_,
        @SuppressWarnings("hiding") TPv _pv_)
    {
        // Constructor
        setIdentif(_identif_);

        setTablevalues(_tablevalues_);

        setEqual(_equal_);

        setRead(_read_);

        setPv(_pv_);

    }

    @Override
    public Object clone()
    {
        return new AReadInstruction(
            cloneNode(this._identif_),
            cloneNode(this._tablevalues_),
            cloneNode(this._equal_),
            cloneNode(this._read_),
            cloneNode(this._pv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReadInstruction(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public PTablevalues getTablevalues()
    {
        return this._tablevalues_;
    }

    public void setTablevalues(PTablevalues node)
    {
        if(this._tablevalues_ != null)
        {
            this._tablevalues_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tablevalues_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public TRead getRead()
    {
        return this._read_;
    }

    public void setRead(TRead node)
    {
        if(this._read_ != null)
        {
            this._read_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._read_ = node;
    }

    public TPv getPv()
    {
        return this._pv_;
    }

    public void setPv(TPv node)
    {
        if(this._pv_ != null)
        {
            this._pv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._tablevalues_)
            + toString(this._equal_)
            + toString(this._read_)
            + toString(this._pv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._tablevalues_ == child)
        {
            this._tablevalues_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._read_ == child)
        {
            this._read_ = null;
            return;
        }

        if(this._pv_ == child)
        {
            this._pv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._tablevalues_ == oldChild)
        {
            setTablevalues((PTablevalues) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._read_ == oldChild)
        {
            setRead((TRead) newChild);
            return;
        }

        if(this._pv_ == oldChild)
        {
            setPv((TPv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
