/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASingleTablevalue extends PTablevalue
{
    private PRealtablevalue _realtablevalue_;

    public ASingleTablevalue()
    {
        // Constructor
    }

    public ASingleTablevalue(
        @SuppressWarnings("hiding") PRealtablevalue _realtablevalue_)
    {
        // Constructor
        setRealtablevalue(_realtablevalue_);

    }

    @Override
    public Object clone()
    {
        return new ASingleTablevalue(
            cloneNode(this._realtablevalue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleTablevalue(this);
    }

    public PRealtablevalue getRealtablevalue()
    {
        return this._realtablevalue_;
    }

    public void setRealtablevalue(PRealtablevalue node)
    {
        if(this._realtablevalue_ != null)
        {
            this._realtablevalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realtablevalue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realtablevalue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realtablevalue_ == child)
        {
            this._realtablevalue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realtablevalue_ == oldChild)
        {
            setRealtablevalue((PRealtablevalue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
