/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASingleExpression extends PExpression
{
    private PSingleexpression _singleexpression_;

    public ASingleExpression()
    {
        // Constructor
    }

    public ASingleExpression(
        @SuppressWarnings("hiding") PSingleexpression _singleexpression_)
    {
        // Constructor
        setSingleexpression(_singleexpression_);

    }

    @Override
    public Object clone()
    {
        return new ASingleExpression(
            cloneNode(this._singleexpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleExpression(this);
    }

    public PSingleexpression getSingleexpression()
    {
        return this._singleexpression_;
    }

    public void setSingleexpression(PSingleexpression node)
    {
        if(this._singleexpression_ != null)
        {
            this._singleexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._singleexpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._singleexpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._singleexpression_ == child)
        {
            this._singleexpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._singleexpression_ == oldChild)
        {
            setSingleexpression((PSingleexpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
