/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASingleparamNparam extends PNparam
{
    private PNparameters _nparameters_;

    public ASingleparamNparam()
    {
        // Constructor
    }

    public ASingleparamNparam(
        @SuppressWarnings("hiding") PNparameters _nparameters_)
    {
        // Constructor
        setNparameters(_nparameters_);

    }

    @Override
    public Object clone()
    {
        return new ASingleparamNparam(
            cloneNode(this._nparameters_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleparamNparam(this);
    }

    public PNparameters getNparameters()
    {
        return this._nparameters_;
    }

    public void setNparameters(PNparameters node)
    {
        if(this._nparameters_ != null)
        {
            this._nparameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nparameters_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nparameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nparameters_ == child)
        {
            this._nparameters_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nparameters_ == oldChild)
        {
            setNparameters((PNparameters) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
