/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ATablevalues extends PTablevalues
{
    private TRb _rb_;
    private PTablevalue _tablevalue_;
    private TLb _lb_;

    public ATablevalues()
    {
        // Constructor
    }

    public ATablevalues(
        @SuppressWarnings("hiding") TRb _rb_,
        @SuppressWarnings("hiding") PTablevalue _tablevalue_,
        @SuppressWarnings("hiding") TLb _lb_)
    {
        // Constructor
        setRb(_rb_);

        setTablevalue(_tablevalue_);

        setLb(_lb_);

    }

    @Override
    public Object clone()
    {
        return new ATablevalues(
            cloneNode(this._rb_),
            cloneNode(this._tablevalue_),
            cloneNode(this._lb_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATablevalues(this);
    }

    public TRb getRb()
    {
        return this._rb_;
    }

    public void setRb(TRb node)
    {
        if(this._rb_ != null)
        {
            this._rb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rb_ = node;
    }

    public PTablevalue getTablevalue()
    {
        return this._tablevalue_;
    }

    public void setTablevalue(PTablevalue node)
    {
        if(this._tablevalue_ != null)
        {
            this._tablevalue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tablevalue_ = node;
    }

    public TLb getLb()
    {
        return this._lb_;
    }

    public void setLb(TLb node)
    {
        if(this._lb_ != null)
        {
            this._lb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rb_)
            + toString(this._tablevalue_)
            + toString(this._lb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rb_ == child)
        {
            this._rb_ = null;
            return;
        }

        if(this._tablevalue_ == child)
        {
            this._tablevalue_ = null;
            return;
        }

        if(this._lb_ == child)
        {
            this._lb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rb_ == oldChild)
        {
            setRb((TRb) newChild);
            return;
        }

        if(this._tablevalue_ == oldChild)
        {
            setTablevalue((PTablevalue) newChild);
            return;
        }

        if(this._lb_ == oldChild)
        {
            setLb((TLb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
