/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class TMainfunc extends Token
{
    public TMainfunc()
    {
        super.setText("main()");
    }

    public TMainfunc(int line, int pos)
    {
        super.setText("main()");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMainfunc(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMainfunc(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMainfunc text.");
    }
}
