<Start>
 <AProgramme>
  <AVideListedecvar>
   <AEpsilon>
   </AEpsilon>
  </AVideListedecvar>
  <ARecursifListedecfonc>
   <ADecfonc>
    <AVideOpttype>
    </AVideOpttype>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AVideListedecvar>
     <AEpsilon>
     </AEpsilon>
    </AVideListedecvar>
    <AInstrbloc>
     <ARecursifListeinst>
      <AEcritureInstr>
       <AExp1Exp>
        <AExp2Exp1>
         <AExp3Exp2>
          <AExp4Exp3>
           <AExp5Exp4>
            <AExp5bExp5>
             <ACarreExp5b>
              <AExp6Exp5b>
               <AParenthesesExp6>
                <AExp1Exp>
                 <AExp2Exp1>
                  <AExp3Exp2>
                   <AExp4Exp3>
                    <AFoisExp4>
                     <AExp5Exp4>
                      <AExp5bExp5>
                       <AExp6Exp5b>
                        <ANombreExp6>
                        </ANombreExp6>
                       </AExp6Exp5b>
                      </AExp5bExp5>
                     </AExp5Exp4>
                     <AExp5bExp5>
                      <AExp6Exp5b>
                       <ANombreExp6>
                       </ANombreExp6>
                      </AExp6Exp5b>
                     </AExp5bExp5>
                    </AFoisExp4>
                   </AExp4Exp3>
                  </AExp3Exp2>
                 </AExp2Exp1>
                </AExp1Exp>
               </AParenthesesExp6>
              </AExp6Exp5b>
             </ACarreExp5b>
            </AExp5bExp5>
           </AExp5Exp4>
          </AExp4Exp3>
         </AExp3Exp2>
        </AExp2Exp1>
       </AExp1Exp>
      </AEcritureInstr>
      <AFinalListeinst>
       <AEpsilon>
       </AEpsilon>
      </AFinalListeinst>
     </ARecursifListeinst>
    </AInstrbloc>
   </ADecfonc>
   <AFinalListedecfonc>
    <AEpsilon>
    </AEpsilon>
   </AFinalListedecfonc>
  </ARecursifListedecfonc>
 </AProgramme>
</Start>
